theme: jekyll-theme-cayman
title: Workshop on Geospatial DRR for Decade of Action (Day 2)
description: A part of Geospatial Capacity Development Conference on GNSS applications and DRR
github: 
  is_project_page: false
  
